### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by vzr314** [jacobnisnevich/material-charts#4]
Dear author, there is an error in documentation published under URL http://jacobnisnevich.github.io/material-charts/

Example code snipped for PIE chart:

```
var examplePieChartData = {
    "datasets": {
      ...
```

It says "dataset**s**" instead of dataset ("datasets" is correct key for for BAR charts, but for PIE charts "dataset" should be used insted) which leads into an error if used.

**Comment by jacobnisnevich** [comment]
Fixed. Thanks for the feedback!
